# Generated by Django 4.2.11 on 2025-03-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('documents_required', 'Documents Required'), ('under_review', 'Under Review'), ('conditionally_accepted', 'Conditionally Accepted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('waitlisted', 'Waitlisted'), ('visa_applied', 'Visa Applied'), ('visa_approved', 'Visa Approved'), ('visa_rejected', 'Visa Rejected'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('canceled', 'Canceled')], default='draft', max_length=30)),
                ('intake_date', models.DateField(help_text='Expected start date for the program')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('consultant', models.ForeignKey(blank=True, limit_choices_to={'role': 'consultant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_applications', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='universities.program')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('transcript', 'Academic Transcript'), ('diploma', 'Diploma/Degree Certificate'), ('cv', 'CV/Resume'), ('recommendation_letter', 'Recommendation Letter'), ('passport', 'Passport'), ('language_test', 'Language Test Score'), ('statement_of_purpose', 'Statement of Purpose'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='application_documents/')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_uploaded', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('documents_required', 'Documents Required'), ('under_review', 'Under Review'), ('conditionally_accepted', 'Conditionally Accepted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('waitlisted', 'Waitlisted'), ('visa_applied', 'Visa Applied'), ('visa_approved', 'Visa Approved'), ('visa_rejected', 'Visa Rejected'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('canceled', 'Canceled')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Application Statuses',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
