# Generated by Django 4.2.11 on 2025-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='duolingo_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gpa_or_percentage',
            field=models.CharField(blank=True, help_text='e.g., 3.8 GPA or 85%', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ielts_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='study_gap_years',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years gap in studies, if any', null=True),
        ),
    ]
