# Generated by Django 4.2.11 on 2025-04-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_duolingo_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Contact email for this application', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mailing_address',
            field=models.TextField(blank=True, help_text='If different from street address', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='telephone_primary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='telephone_secondary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
