# Generated by Django 4.2.11 on 2025-04-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='fee_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approximate annual fee in USD', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='intake_details',
            field=models.TextField(blank=True, help_text='Information about application intakes (e.g., Fall, Spring, Rolling)', null=True),
        ),
    ]
